server:
  port: 7070  # Puerto donde se levantará el Config Server

spring:
  application:
    name: config-server  # Nombre de la aplicación (útil si usas Eureka u otros servicios)

  cloud:
    config:
      server:
        git:
          uri: https://github.com/keinraf/Microservicios-KEVINRAF-MANUAL.git
          # URI del repositorio Git donde están los archivos de configuración centralizados
          # Este repositorio debe contener archivos como application.yml, ms-insidencia-service.yml, etc.

          searchPaths: config-data
          # Carpeta dentro del repositorio donde buscará los archivos .yml
          # Ejemplo: config-data/ms-insidencia-service.yml

          default-label: principalkr
          # Rama por defecto (branch) desde donde leerá la configuración
          # Asegúrate que la rama exista en el repositorio

  security:
    user:
      name: kevinraf           # Usuario básico para proteger el Config Server
      password: futurojuntos<3 # Contraseña (puede ser cifrada en producción)
